### ISSUE TITLE
Lowercase to uppercase needed for "cf" in "cf CLI" in the scroll menu

### ISSUE THREAD

**Issue by ishitar** [cloudfoundry/docs-cloudfoundry-concepts#124]
![pcf](https://user-images.githubusercontent.com/41416752/67144472-57956180-f294-11e9-99a6-41c6657dab9f.png)

**Comment by ericpromislow** [comment]
I thought that casing was deliberately chosen to indicate "cf" as the name
of the command-line utility, always typed in lower-case, from "CLI", which
is a conceptual acronym.

**Comment by mjgutermuth** [comment]
Hi @ishitar! Thanks for reaching out to us. Like @ericpromislow mentioned, we intentionally use lowercase when we refer to the cf CLI. We do this to make it clear when we're talking about the CLI tool instead of the Cloud Foundry platform, which we sometimes see abbreviated to CF.

We are happy to hear feedback, and if you want to discuss this or anything else related to the docs, feel free to chat with us in the [#cf-docs](https://cloudfoundry.slack.com/messages/C03B0T0D5) channel of Cloud Foundry Slack!
