### ISSUE TITLE
The Diego Acceptance Tests are long gone

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/docs-cloudfoundry-concepts#16]
The link works, but takes you to a page pointing to  https://github.com/cloudfoundry/cf-acceptance-tests

**Comment by bentarnoff** [comment]
@ericpromislow Thanks for your request. I've searched docs-cloudfoundry-concepts and am unable to find references to Diego Acceptance Tests or a link to https://github.com/cloudfoundry/cf-acceptance-tests. I believe this issue may have already been resolved. I'm closing this request, but please resubmit with a precise page location if you believe I've missed something. Thanks.

**Comment by bentarnoff** [comment]
@ericpromislow It turns out I was unable to find references to Diego Acceptance Tests in docs-cloudfoundry-concepts because I was searching our staging site, where the "Monitoring and Testing" section has been broken out into a new topic called "Monitoring and Testing Diego Components" located in another, OSS-only repo, docs-running-cf. I've gone into that new topic and changed the discussion of Diego Acceptance Tests to CF Acceptance Tests, and included the link to the cf-acceptance-tests repo. When our staging material is pushed to prod, you should see this change live. Thanks!
