### ISSUE TITLE
Dev details for app mTLS

### ISSUE THREAD

**Issue by somehowchris** [cloudfoundry/docs-cloudfoundry-concepts#168]
I'm a real fan of cf and just learned about mTLS, had a search for mTLS inside cf and found https://docs.cloudfoundry.org/concepts/http-routing.html#tls-to-back-end.

Since its in the general `concepts` part of the webpage I got hooked and had a bit more research. As a dev I couldn't find any reference on something like `use these certs for mtls` or `heres how you get started`. There are a lot of references to set it up behind the scenes but again I couldn't find a part on which certs I should host or accept.

Is this meant to be? Did I miss something?

**Comment by ameowlia** [comment]
Hi @anita-flegg, 

The tls (or mtls) traffic from gorouter to the app backend "just works". There is nothing that the app has to do. This isn't spelled out on the page linked and definitely could be.


This "just works" because gorouter does not talk directly to the backend app. It talks to the envoy sidecar. There is an envoy sidecar in every app container. The envoy sidecar has the correct certs needed to do mtls with gorouter. So the gorouter and the envoy commuicate via tls (or mtls), then the envoy proxies on the unencrypted traffic directly to the app process. Voila! The power of the CF platform.

```
 Router VM                   Diego Cell VM
┌───────────────────┐       ┌──────────────────────────────────┐
│                   │       │                                  │
│                   │       │                                  │
│                   │       │   App Container                  │
│                   │       │  ┌─────────────────────────────┐ │
│                   │       │  │                             │ │
│    ┌────────┐     │       │  │ ┌─────┐       ┌───────────┐ │ │
│    │gorouter├─────┼───────┼──┤►│envoy├──────►│app process│ │ │
│    └────────┘     │       │  │ └─────┘       └───────────┘ │ │
│                   │       │  │                             │ │
│                   │       │  └─────────────────────────────┘ │
│                   │       │                                  │
└───────────────────┘       └──────────────────────────────────┘
```

**Comment by anita-flegg** [comment]
This is actually discussed in the section called Preventing mis-routes, but it's also needed earlier in the topic.

I've added this extra detail to the section called "TLS to apps and other back end services."
