### ISSUE TITLE
Use variable _oss_roles_table.html.md.erb

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/docs-cloudfoundry-concepts#26]
I think we should replace `[feature flag](../adminguide/listing-feature-flags.html)` in `_oss_roles_table.html.md.erb` with a variable from the book. I need to use this page in my docs but I have no interest in having the whole Admin Guide so I would like to replace it with the string "feature flag".

--> Let's add this as a variable as we do for `vars.services_link`

**Comment by pspinrad** [comment]
Hi Tobias-- this is Paul from PCF docs in SF.  For this story and also:
cloudfoundry/docs-cloudfoundry-concepts #27: replace services with link
https://www.pivotaltracker.com/story/show/121501049

...I'm wondering why you want to use the template variables, whether it's because it makes sense in general design terms, or because you have a specific need for those variables, to help you produce your own version of the docs.  In general, we want to minimize use of those template variables, but if there's a specific reason to put them in, that's fine.  Please let me know, I appreciate your contributing, and I'd be happy to discuss-- thanks!

**Comment by pspinrad** [comment]
Hi Tobias-- thanks for the explanation. I tried this, using a new template var feature_flag within the partial _oss_roles_table, which is pointed to by the template var roles_table in the file concepts/roles.html -- but running bookbinder on this arrangement seems to put it into an endless error loop or something-- it wouldn't come back and I couldn't access the topic.

So I'm guessing that we can't do this kind of thing with current tools, I'm sorry.  Too deeply nested for our ruby-markdown-html processing.  Or please let me know if you get it to work or have another explanation.
